add support for reading .j2 config files with jinja
chime-experiment/coco pull request #246
Opened 2022-06-09 19:02 UTC by aelanman

2022-06-09 20:05 UTC, andrerenard requested changes
I think we should add `jinja2` to the `requirements.txt` file.

2022-06-13 15:28 UTC, aelanman commented
@andrerenard I've updated the requirements and marked this PR ready for review

2022-06-13 18:25 UTC, jrs65 commented
Is it worth trying to centralise the parsing of Jinja files into configs that kotekan will read? It would be nice to avoid the issue of having potentially divergent schemes for doing this parsing.

This would require solving the issue that kotekan simply embeds its processing into `kotekan.cpp`.

2022-06-13 18:46 UTC, andrerenard commented
Perhaps this is a worth a wider discussion on the call this week, but I'm hesitant move to a model which calls python first to parse things and then calls kotekan.  It could be done, but it creates some potential issues around how logging and debuggers/GPU profilers work.   In most production situations kotekan runs as a service and it really has no need for python, and there is no reason to run it through a wrapper.  So I could see being in a world where we end up with different files to run in different modes.  If we just want to make sure we are parsing the same way (not that we are doing anything fancy yet) we could just call the `python/scripts/config_to_json.py` script in the kotekan which is the source for the `kotekan.cpp` call.

2022-06-13 18:57 UTC, andrerenard approved these changes
Notwithstanding @jrs65's concerns about centralizing the parsing logic, this looks good to me.   However, I think we should try to get the `aioredis_v2` branch merged into main before we merge this, since the way the CI is configured we aren't running the new unit test here.  And it would be nice to keep the `aioredis` changes as a separate PR from this.

2022-06-13 19:12 UTC, jrs65 commented
> If we just want to make sure we are parsing the same way (not that we are doing anything fancy yet) we could just call the `python/scripts/config_to_json.py` script in the kotekan repo which is the source for the `kotekan.cpp` call.

I would suggest doing this:

- Create a python module as part of the kotekan python package that has routines for doing all the parsing.
- Adding a `if __name__ == "__main__"` block to it such that it runs directly as a script *without* needing the package to be installed.
- Have `coco` install the kotekan python package and use the API from the new parsing module.
- Have `kotekan` either run the python script from an installed location in the fs, or have CMake embed the script at build time in a `.h` file, and have kotekan compile the string version of the script into the binary from that file (but otherwise run as it currently does).

I think that can be made to conveniently work in all envisaged cases from a single implementation.

However, we might want to pause on merging this PR until we've figured out what to do as in the case above the logic ends up exclusively in the kotekan python package.

2022-06-13 19:13 UTC, jrs65 commented
Agree. That we should merge the aioredis branch first. Currently it fails a bunch of the linting and doc building tests though.

2022-06-13 19:21 UTC, andrerenard commented
@jrs65 I really like that proposal, and I'll also vote we implement this as a python package in the kotekan repo.   That also makes it easier and more consistent for projects that want to use something other than `coco` for system control.

2022-06-13 19:24 UTC, andrerenard requested changes, later dismissed
Changing this to "changes needed", in response to @jrs65's proposal, which I think we should implement.

2022-06-17 01:59 UTC, aelanman commented
@andrerenard @jrs65 I've adjusted this accordingly with the changes in kotekan. I set the requirements.txt file to install the version of kotekan on the `ael/jinja` branch so the tests could pass, but I'll need to set that back to `develop` once that branch is merged.
https://github.com/kotekan/kotekan/pull/1030

2022-09-08 20:40 UTC, jrs65 commented
@aelanman if you update this now #242 is merged I can take another look.

2022-12-06 21:23 UTC, aelanman commented
@andrerenard @jrs65  I thought this was merged earlier today, but was mistaken. Is there anything else needed for this to be merged?

2023-01-18 20:23 UTC, jrs65 approved these changes, later dismissed

2025-09-17 15:42 UTC, aelanman commented
@andrerenard This PR is quite stale at this point. Should I merge it?

2025-09-17 15:45 UTC, andrerenard commented
Oh yeah we should get this in, we'll need it for the CHIME upgrade as well.   I'm just going to check with @ketiltrout that nothing here creates any operational issues for CHIME's existing setup.

2026-03-13 00:25 UTC, ljgray requested changes

2026-03-13 00:25 UTC, ljgray commented on requirements.txt
> +kotekan @ git+https://github.com/kotekan/kotekan.git@ael/py3_only#egg=kotekan&subdirectory=python/
I doubt that we would want this to depend on a fairly out-of-date branch of kotekan

2026-03-13 00:41 UTC, ketiltrout commented on requirements.txt
> +kotekan @ git+https://github.com/kotekan/kotekan.git@ael/py3_only#egg=kotekan&subdirectory=python/
The point of this requirement seems to be: coco is using kotekan's `load_config_file` function to handle the jinja templating.  I suspect, since the call to `load_config_file` is using fixed values for all the parameters (except the filename), that if we just re-implemented it locally, without those extra parameters, it would boil down to something like:
```
if file.endswith(".j2")
    # do jinja templating to get YAML
else:
   # load YAML from disk

# run whatever YAML you got above through yaml.load
```

2026-03-13 00:54 UTC, ljgray commented
The tests are failing because of a python version mismatch with `comet`, which requires >= 3.10. I kind of want to make version changes in a different PR, though

2026-03-13 01:05 UTC, ljgray commented
@aelanman We're hoping to finally get this merged so we can use it with the chime upgrade, so just wanted to ping you to make sure that merging and deleting this branch doesn't break anything on your end. Note that we're merging into the `chime-upgrade` branch for now.

2026-03-13 13:46 UTC, aelanman commented
Hi @ljgray -- sounds good! Please let me know if I can help in any way.

2026-03-13 21:57 UTC, ketiltrout approved these changes
We're going to have to do something about the test suite.

And we should migrate to pyproject.

And also ruff.

But none of that should happen in this PR.

In addition to the Jinja2 stuff really like the `get-coco-config` which means we don't need to install the endpoints with the client.  That's definitely an improvement.

We need to come up with a test plan for the upgrade.

2026-03-13 21:57 UTC, ketiltrout commented on .github/workflows/main.yaml
> +        uses: supercharge/redis-github-action@1.4.0
```suggestion
        uses: supercharge/redis-github-action@1.8.1
```
We might as well update this to the latest.

2026-03-13 21:57 UTC, ketiltrout commented on coco/test/coco_runner.py
> +            print(err)
I don't understand the point here: `err` is already printed on the prior line.

2026-03-13 23:27 UTC, ljgray commented
Merging this into the `chime-upgrade` branch. We'll make some more PRs to fix the tests.

2026-03-13 23:27 UTC, merged